config/routes.rb
GoalTracker::Application.routes.draw do

  root :to => 'pages#index'
  
  get 'dashboard' => 'pages#dashboard'

  resources :user_sessions

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  resources :users
  
  resources :goals
  
  get "moments" => 'moments#index', :as => "moments"
  
  get "moments/new" => 'moments#new', :as => "new_moment"

  post "moments" => 'moments#create'

  get "moments/edit"

  put "moments/update"

  get "moments/destroy"

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation
  has_many :goals
  
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]
  
  # GET /users
  # GET /users.json
  def index
    User.delete_all
    Goal.delete_all
    Moment.delete_all
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_id(params[:id])
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        
        TrackerMailer.delay.welcome(@user)

        auto_login(@user)
        format.html { redirect_to goals_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @goal = Goal.find_by_user_id(@user.id)
    if @goal != nil
      @goal.destroy
      @moment = Moment.find_by_goal_id(@goal.id)
      if @moment != nil
        @moment.destroy
      end
    end
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= f.label :email %></p>
    <p><%= f.text_field :email %></p>
  </div>
  <div class="field">
    <p><%= f.label :password %></p>
    <p><%= f.password_field :password %></p>
  </div>
  <div class="field">
    <p><%= f.label :password_confirmation %></p>
    <p><%= f.password_field :password_confirmation %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="editUser">
  <h1>Editing user</h1>

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <p><%= f.label :email %></p>
      <p><%= f.text_field :email %></p>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>


  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="userListing">
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user_path(user) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<p><%= link_to 'New User', new_user_path %></p>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="showUser">
<p id="notice"><%= notice %></p>

<p>
  <span>Email:</span>
  <%= @user.email %>
</p>

<h2>Goals</h2>
<% @user.goals.each do |g| %>
  <p>
    <%= link_to "goal", goal_path(g.id) %> - <%= g.goal_value %>
  </p>
<% end %>

<p>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</p>
</div>