config/routes.rb
GoalTracker::Application.routes.draw do

  root :to => 'pages#index'
  
  get 'dashboard' => 'pages#dashboard'

  resources :user_sessions

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  resources :users
  
  resources :goals
  
  get "moments" => 'moments#index', :as => "moments"
  
  get "moments/new" => 'moments#new', :as => "new_moment"

  post "moments" => 'moments#create'

  get "moments/edit"

  put "moments/update"

  get "moments/destroy"

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :goal_value, :title
  belongs_to :user
  has_many :moments

  # Internal: Determine the difference in time between Time.now and when last moment was created
  #
  # self.moments - the Array of Moments belonging to a particular Goal
  #
  # Example:
  #
  # goal_object.seconds_since_last_moment_created
  # => 145003
  #
  # Returns the seconds since a moment was created for a goal
  def seconds_since_last_moment_created
    Time.now - self.moments.last.created_at    
  end
  
  def time_since
    self.check_time / 60
  end

  # Internal: Determines whether user needs an email notification of goal inactivity and sends email if too much time has lapsed; checks every Goal for a User
  #
  # time_in_seconds - the maximum amount of seconds to pass since creation of Moment for a Goal
  #
  # Example:
  #
  # Goal.check_for_laziness
  # => [#<Goal id: 2, title: "goal 2", goal_value: 500, user_id: nil, completed: nil, created_at: "2014-10-08 17:20:33", updated_at: "2014-10-08 17:20:33">,
 #<Goal id: 1, title: "goal 1", goal_value: 25, user_id: 1, completed: nil, created_at: "2014-10-08 17:01:45", updated_at: "2014-10-08 20:59:19">]
 #
 # Returns an Array of a table Goal objects that will receive email reminders
  def self.check_for_laziness(time_in_seconds)
    goals = Goal.all
    email_list=[]
    goals.each do |g|
      user = User.find_by_id(g.user_id)
      if g.moments.length >= 1
        if g.seconds_since_last_moment_created > time_in_seconds
          TrackerMailer.delay.reminder(user)
          email_list << g
        end
      end
    end
    return email_list
  end
  
  def momentum
    if self.moments.length > 0
      self.moments.sum(:moments_value)
    else
      0
    end
  end
  
  def percent_completed
    if self.momentum >= self.goal_value
      100
    else
      (self.momentum*100)/self.goal_value
    end
  end

  #   if self.moments.last > 0
  #     accumulated=self.moments.last.accum_value
  #   else
  #     accumulated=0
  #   end
  #   total=self.goal_value
  #   if accumulated >= total
  #     100
  #   else
  #     (accumulated*100)/total
  #   end
  # end
  
  def goal_reached?(goal)
    if goal.moments.sum(:moment_value) >= goal.goal_value
      true
    else
      false
    end
  end
  
  def goal_completed?(goal)
    if goal_reached?(goal)
      goal.completed = true
    else
      goal.completed = false
    end
  end
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  # GET /goals
  # GET /goals.json
  def index
    @goals = current_user.goals

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goals = Goal.all
    @goal = Goal.find_by_id(params[:id])
    @goal.goal_completed?(@goal)
    @moment = Moment.new
    @moments = @goal.moments
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal}
    end
  end

  # GET /goals/new
  # GET /goals/new.json
  def new
    @goal = Goal.new
    @user=User.find_by_id(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/1/edit
  def edit
    @goal = Goal.find(params[:id])
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(params[:goal])
    @goal.user_id = current_user.id

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @goal }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    @goal = Goal.find(params[:id])

    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>

  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :goal_value %><br />
    <%= f.number_field :goal_value %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Listing goals</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Goal value</th>
    <th>User</th>
    <th>Completed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @goals.each do |goal| %>
    <tr>
      <td><%= goal.title %></td>
      <td><%= goal.goal_value %></td>
      <td><%= goal.user_id %></td>
      <td><%= goal.completed %></td>
      <td><%= link_to 'Show', goal_path(goal.id) %></td>
      <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
      <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<p><%= link_to 'New Goal', new_goal_path %></p>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<div class="nav">
  <ul>
    <% @goals.each do |g| %>
      <li><%= link_to g.title, goal_path(g.id) %></li>
    <% end %>
  </ul>
</div>


<%= content_tag :div, " ", id: "showChart", data: {moments: @moments} %>

<div class="createMoment">
  <p><span>Create Moment</span></p>
  <%= form_for @moment do |f| %>

    <p>
      <%= f.label :moment_value %>
      <%= f.number_field :moment_value %>
      <%= f.hidden_field :goal_id, {:value => @goal.id}%>
    </p>
    <%= f.submit %>
  <% end %>
</div>

<div class="currentMoment">
  <p>
    <span>Title:</span> <%= @goal.title %>
  </p>

  <p>
    <span>Goal value:</span> <%= @goal.goal_value %>
  </p>

  <% if @goal.moments.length > 0 %>
    <span>Moments</span>
    <% @goal.moments.reverse.first(5).each do |m| %>  <!-- descending -->
      <p><%= m.moment_value %> - <%= m.created_at %></p>
    <% end %>
  <% end %>
</div>


  