config/routes.rb
GoalTracker::Application.routes.draw do

  root :to => 'pages#index'
  
  get 'dashboard' => 'pages#dashboard'

  resources :user_sessions

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  resources :users
  
  resources :goals
  
  get "moments" => 'moments#index', :as => "moments"
  
  get "moments/new" => 'moments#new', :as => "new_moment"

  post "moments" => 'moments#create'

  get "moments/edit"

  put "moments/update"

  get "moments/destroy"

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalTracker</title>
  
  <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.5.1.css">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<header class="clearfix">
  <div class="logo">
    <span>Goal Tracker</span>
  </div>

  <% if flash[:notice] || flash[:alert] %>
  <div class="messages">
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
  <% end %>

  <div id="nav">
    <% if current_user %>
      <p><%= link_to "Dashboard", dashboard_path %> |</p>
      <p><%= link_to "Logout", :logout, method: :post %></p>
    <% else %>
      <p><%= link_to "Register", new_user_path %> |</p>
      <p><%= link_to "Login", :login %></p>
    <% end %>
  </div>
  
</header>
  <body> 
    <div class="content clearfix">

      <%= yield %>
    
    </div>
  </body>

<footer>  
  <% if @goal %>
    <p>
      <%= link_to 'Edit', edit_goal_path(@goal) %> |
      <%= link_to 'Back', goals_path %> 
    </p>
  <% end %>
</footer>

</html>